### ISSUE TITLE
Output is not merging i.e after running scan result is not stored of both scan.

### ISSUE THREAD

**Issue by m14r41** [saim1011/SubEnum#1]
See, output shows only for first scan in file, but not for 2nd scan. I think there is some issue in script.

**Comment by saim1011** [comment]
Okey, Let me check
Thank for your review.

**Comment by m14r41** [comment]
I've spot the issues. The name while merging is incorrect.

**Comment by saim1011** [comment]
Great, please send PR if poosbile.
Thanks!

**Comment by m14r41** [comment]
Sure, I'll do

**Comment by saim1011** [comment]
Thanks for PR, Now isse is resolved.
Enjoy : )
